# Generated by Django 3.0.5 on 2020-04-30 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('adm_rate', models.FloatField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('SAT_math', models.IntegerField(blank=True, null=True)),
                ('SAT_EBRW', models.IntegerField(blank=True, null=True)),
                ('ACT_composite', models.IntegerField(blank=True, null=True)),
                ('in_state_cost', models.IntegerField(blank=True, null=True)),
                ('out_state_cost', models.IntegerField(blank=True, null=True)),
                ('institution_type', models.CharField(blank=True, choices=[('Public', 'Public'), ('Private nonprofit', 'Private nonprofit'), ('Private for-profit', 'Private for-profit')], max_length=30)),
                ('grad_debt_median', models.IntegerField(blank=True, null=True)),
                ('completion_rate', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('majors', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('sat', models.IntegerField(blank=True, null=True)),
                ('act', models.IntegerField(blank=True, null=True)),
                ('num_students', models.IntegerField(blank=True, null=True)),
                ('grad_rate', models.FloatField(blank=True, null=True)),
                ('ap_enroll', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('residence_state', models.CharField(blank=True, max_length=2, null=True)),
                ('high_school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('high_school_city', models.CharField(blank=True, max_length=100, null=True)),
                ('high_school_state', models.CharField(blank=True, max_length=2, null=True)),
                ('major_1', models.CharField(blank=True, max_length=100, null=True)),
                ('major_2', models.CharField(blank=True, max_length=100, null=True)),
                ('GPA', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('college_class', models.IntegerField(blank=True, null=True)),
                ('ACT_English', models.IntegerField(blank=True, null=True)),
                ('ACT_math', models.IntegerField(blank=True, null=True)),
                ('ACT_reading', models.IntegerField(blank=True, null=True)),
                ('ACT_science', models.IntegerField(blank=True, null=True)),
                ('ACT_composite', models.IntegerField(blank=True, null=True)),
                ('SAT', models.IntegerField(blank=True, null=True)),
                ('SAT_math', models.IntegerField(blank=True, null=True)),
                ('SAT_EBRW', models.IntegerField(blank=True, null=True)),
                ('SAT_literature', models.IntegerField(blank=True, null=True)),
                ('SAT_US_hist', models.IntegerField(blank=True, null=True)),
                ('SAT_world_hist', models.IntegerField(blank=True, null=True)),
                ('SAT_math_I', models.IntegerField(blank=True, null=True)),
                ('SAT_math_II', models.IntegerField(blank=True, null=True)),
                ('SAT_eco_bio', models.IntegerField(blank=True, null=True)),
                ('SAT_mol_bio', models.IntegerField(blank=True, null=True)),
                ('SAT_chemistry', models.IntegerField(blank=True, null=True)),
                ('SAT_physics', models.IntegerField(blank=True, null=True)),
                ('num_AP_passed', models.IntegerField(blank=True, null=True)),
                ('high_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.HighSchool')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('denied', 'denied'), ('deferred', 'deferred'), ('waitlisted', 'waitlisted'), ('withdrawn', 'withdrawn')], max_length=10)),
                ('questionable', models.BooleanField(default=False)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.College')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Student')),
            ],
        ),
    ]
