# Generated by Django 3.0.4 on 2020-03-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_highschool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='acceptance_rate',
        ),
    ]
