# Generated by Django 3.0.4 on 2020-03-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_college_acceptance_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='ranking',
            field=models.IntegerField(default=-1),
        ),
    ]
