@startuml
left to right direction

component "Web Browser" as wb

rectangle c4me {
    component "StudentAPI" as student
    component "AdminAPI" as admin
    component "Django (Web Server)" as ws
    component "React (View Layer)" as react
    component "Student Profile DB" as sdb 
    component "College DB" as cdb
    component "High School DB" as hsdb 
}

component "College Data Sources" as cds
component "High School Data Source" as hsds
component "Test Data Source" as tds


'Data reliance
cdb -(0- cds
cdb -(0- tds
hsdb -(0- hsds
hsdb -(0- tds

ws -(0- student
ws -(0- admin


student -(0- sdb
student -(0- cdb
student -(0- hsdb

admin -(0- sdb
admin -(0- cdb
admin -(0- hsdb



wb -(0 react 
react -(0- ws 


 
note left of student : Not an actor, but the component that provides student functionality

@enduml