@startuml frontend
'left to right direction

class App{
    +user: state
}
class "React"{
}
App -(0- "React"
App -(0- "react-router"
App -(0- "material-ui"


class HomeScreen{
    +handleSearch(event): void
}

class ProfileScreen{
    +submitEditForm(event): boolean
}

class NavigationBar{
    userAvatar: Image
}

App o-- NavigationBar

class SearchPageScreen{
    +searchResult: State
    +recommender: State
    +sortCriteria: State
    +filterCriteria: State
    +updateSearchForm(event): void
    +recommendColleges(): void
}

class CollegeCard{
    +collegeName: String 
    +collegeRanking: Integer
    +collegeType: String
    +recommendationScore: Integer
    +viewCollege():void
}
SearchPageScreen*--CollegeCard

class CollegeProfileScreen{
}  

class ApplicationTracker{
    +similarHighSchools: State
    +studentList: State
    +filterCriteria: State
    +handleSearchSimilarHighSchool(event): void
    +handleUpdateFilter(event): void
}
class StudentCard{
    +studentName: String    
    +studentGPA: Float
    +studentScores: Integer
    +studentHighSchool: String
    +viewStudentProfile():void
}
StudentCard -* ApplicationTracker
CollegeProfileScreen *-- ApplicationTracker

class LoginScreen{
    +submitLoginForm(event): user
} 

class RegisterScreen{
    +submitSignupForm(event): user
}


App o-- HomeScreen
App o-- ProfileScreen
App o-- SearchPageScreen
App o-- CollegeProfileScreen
App o-- LoginScreen
App o-- RegisterScreen



@enduml