@startuml
'left to right direction

class App{
    +user: state
    +errorMessage: state
}
class "React"{
}
App -(0- "React"


class NavigationBar{
    +handleLogout(): void
    +handleSearch(event): void
}

class HomeScreen{
    +handleSearch(event): void
}

class SearchPageScreen{
    +colleges: State
    +act: State
    +cost: State
    +ranking: State
    +SATebrw: State
    +SATmath: State
    +size: State
    +admissionRate: State
    +sort: State
    +loading: State
    +handleSearch(event): void
    +setOrder():void
    +recommendColleges(): void
}

class CollegeCard{
    +renderInfo():View
}
class Sorting{
    +handleChangeSort(event): void
}

package Filters{
    class LocationFilter{
        +handleSelectState(event):void
    }
    class MajorFilter{
        +handleSelectMajor(event):void
    }
    class SizeFilter{
        +checkedSizes: State
        +handleSizeChange(event):void
    } 
    class SliderFactory{
        +value: State
    }
}

SearchPageScreen o-- CollegeCard
SearchPageScreen o-- Sorting
SearchPageScreen o-- Filters


class CollegeProfileScreen{
    +college: State
} 

class CollegeInfoCard{
    +majors: [] String
}

class ApplicationTracker{
    +similarHighSchools: State
    +studentList: State
    +filterCriteria: [] State
    +handleSearchSimilarHighSchool(event): void
    +handleUpdateFilter(event): void
}

CollegeProfileScreen o-- ApplicationTracker
CollegeProfileScreen o-- CollegeInfoCard

class StudentCard{
    +studentName: String    
    +studentGPA: Float
    +studentScores: Integer
    +studentHighSchool: String
    +viewStudentProfile():void
}

StudentCard -o ApplicationTracker


class StduentProfileScreen{
    +currentStudent: State
    +submitEditForm(event): boolean
    +checkForQuestionale(string): boolean
}

class LoginScreen{
    +handleLogin(event): 
} 

class RegisterScreen{
    +handleRegister(event): void
    +validateEmail(string): boolean
}

App o-- NavigationBar
App o-- HomeScreen
App o-- StduentProfileScreen
App o-- SearchPageScreen
App o-- CollegeProfileScreen
App o-- LoginScreen
App o-- RegisterScreen



@enduml