@startuml

left to right direction

component "web browser" as wb
component "web server" as ws
component "gui framework" as gui
component "relational database" as rdb
' component "persistance framework" as fram 

rectangle c4me {
    component "College DB" as col
    component "High School DB" as hs 
    component "student" as stud 
    component "authentication" as auth 
    component "Data Sync" as ds 
}

wb -(0- ws : HTTP
ws -(0- c4me 
stud -(0- hs : Persistance Framework
stud -(0- col : Persistance Framework
stud -(0- auth
hs -- ds
col -- ds
ds -- rdb


@enduml